# Generated by Django 5.2.7 on 2025-11-06 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditFileUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('remark', models.CharField(default='Audit File Update', max_length=100)),
                ('status', models.CharField(blank=True, default='Running', max_length=20, null=True)),
                ('script', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_file_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_audit_file_update',
                'ordering': ('-create_dt',),
                'unique_together': {('user', 'create_dt')},
            },
        ),
        migrations.CreateModel(
            name='DBUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('remark', models.CharField(default='DB Update', max_length=100)),
                ('status', models.CharField(blank=True, default='Running', max_length=20, null=True)),
                ('script', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_db_update',
                'ordering': ('-update_dt',),
                'unique_together': {('appname', 'user', 'create_dt')},
            },
        ),
    ]
